[config]
model = "gemini-3-flash-preview"
model_turbo = "gemini-3-flash-preview"
fallback_models = ["gpt-5.2-mini"]
response_language = "zh-TW"
label_suggestions = true

[pr_description]
extra_instructions = "answer in Traditional Chinese"

[pr_reviewer]
extra_instructions = "answer in Traditional Chinese"
ignore_files = ["pubspec.lock", "*.g.dart", "*.freezed.dart", "ios/Podfile.lock", "android/gradle.properties", "web/**/*"]

[pr_code_suggestions]
extra_instructions = "answer in Traditional Chinese"
ignore_files = ["pubspec.lock", "*.g.dart", "*.freezed.dart", "ios/Podfile.lock", "android/gradle.properties", "web/**/*"]

[pr_update_changelog]
push_changelog_changes = true
extra_instructions = "answer in Traditional Chinese"